Window.SetBackgroundTopColor(0.02, 0.025, 0.04);
Window.SetBackgroundBottomColor(0.02, 0.025, 0.04);

logo_image = Image("missouri-logo.png");
logo_sprite = Sprite(logo_image);

logo_sprite.SetX(
    Window.GetWidth() / 2 - logo_image.GetWidth() / 2
);

logo_sprite.SetY(
    Window.GetHeight() / 2 - logo_image.GetHeight() / 2
);

progress = 0;

fun refresh_callback ()
{
    progress += 0.08;

    if (progress > 6.28)
        progress = 0;

    logo_sprite.SetOpacity(
        0.75 + 0.25 * Math.Sin(progress)
    );
}

Plymouth.SetRefreshFunction(refresh_callback);
